### ISSUE TITLE
Customized token parsing functions passed into `.specifyrc.js`

### ISSUE THREAD

**Issue by ridafkih** [Specifyapp/parsers#164]
Would we be willing to add the ability to provide parsing functions into the `.specifyrc.js` file in order to allow for further customize-ability without having to create PRs to create custom parsers?

This would allow developers to pass in a function that would be used to manipulate the names of different keys, filenames, etc., rather than working solely with the preconfigured parsers.

**Comment by ridafkih** [comment]
PR #165 is a complete implementation of what this feature would look like.

**Comment by AMoreaux** [comment]
Hi @ridafkih

Custom code inside parsers and custom parsers are on our roadmap. But there is a big security concern with these features. 

Since parsers are executed on Specify servers, we need to be sure that the custom code is safe. We will create a service to run untrust code in a completely isolated environment. But today, it's not yet possible.

We can still share a private GitHub repository to collaborate on private custom parsers. Tell me if this is a thing that could fix the issue.
